In [1]:
import numpy as np
import pandas as pd

In [2]:
#Reading data
test_data = pd.read_csv('coursera_sessions_test.txt', delimiter=';', names=['looked','bought'])
train_data = pd.read_csv('coursera_sessions_train.txt', delimiter=';', names=['looked','bought'])
test_data.head()

looked bought
0              6,7,8    NaN
1           13,14,15    NaN
2              22,23    NaN
3  28,29,30,31,32,33    NaN
4              40,41    NaN

### 1. Подготовительные работы

In [3]:
def get_freq_list(data):
    l = list()
    for string in data:
        id_list = string.strip().split(',')
        l += id_list
    l = list(map(int, l))
    frequency_qty = np.bincount(l)
    print(frequency_qty)
    non_zero_ids = np.nonzero(frequency_qty)[0]
    print(non_zero_ids)
    return list(zip(non_zero_ids, frequency_qty[non_zero_ids]))

In [4]:
# looks
train_looks = get_freq_list(list(train_data['looked']))
train_looks_data = pd.DataFrame(train_looks, columns=['id','looks']).set_index('id')

# buys
train_data_b = train_data['bought'].dropna()
train_buys = get_freq_list(list(train_data_b))
train_buys_data = pd.DataFrame(train_buys, columns=['id','buys']).set_index('id')

[6 6 9 ... 1 1 1]
[     0      1      2 ... 102804 102805 102806]
[0 0 0 ... 0 0 1]
[     5      6      7 ... 102417 102462 102646]


In [5]:
train_looks_buys_data = train_looks_data.join(train_buys_data)
train_looks_buys_data= train_looks_buys_data.fillna(0)
train_looks_buys_data

train_looks_buys_data['looked_rank'] = train_looks_buys_data.looks.rank(ascending=False)
train_looks_buys_data['bought_rank'] = train_looks_buys_data.buys.rank(ascending=False)
train_looks_buys_data

looks  buys  looked_rank  bought_rank
id                                           
0           6   0.0      14211.5      40715.0
1           6   0.0      14211.5      40715.0
2           9   0.0       8828.0      40715.0
3           7   0.0      11933.5      40715.0
4          11   0.0       6734.0      40715.0
5           4   1.0      21598.5       2473.0
6         283   2.0          9.0        367.0
7         312   2.0          6.0        367.0
8         225   3.0         13.0        110.0
9           7   0.0      11933.5      40715.0
10          7   0.0      11933.5      40715.0
11          5   0.0      17263.5      40715.0
12         17   0.0       3508.0      40715.0
13         10   0.0       7697.5      40715.0
14          4   0.0      21598.5      40715.0
16         36   0.0        958.5      40715.0
17         70   2.0        251.0        367.0
18         11   0.0       6734.0      40715.0
19         35   0.0       1011.5      40715.0
20         48   0.0        555.5      40715.0
21         11   0.0       6734.0      40715.0
22         37   0.0        910.0      40715.0
23         19   0.0       2913.5      40715.0
24          7   0.0      11933.5      40715.0
25          6   0.0      14211.5      40715.0
26          7   0.0      11933.5      40715.0
27         15   0.0       4274.0      40715.0
28        148   3.0         51.0        110.0
29         16   1.0       3875.0       2473.0
30         29   1.0       1434.5       2473.0
...       ...   ...          ...          ...
102752      1   0.0      61559.5      40715.0
102753      1   0.0      61559.5      40715.0
102761      1   0.0      61559.5      40715.0
102762      1   0.0      61559.5      40715.0
102763      1   0.0      61559.5      40715.0
102764      1   0.0      61559.5      40715.0
102765      1   0.0      61559.5      40715.0
102766      1   0.0      61559.5      40715.0
102767      1   0.0      61559.5      40715.0
102776      1   0.0      61559.5      40715.0
102777      1   0.0      61559.5      40715.0
102778      1   0.0      61559.5      40715.0
102779      1   0.0      61559.5      40715.0
102780      1   0.0      61559.5      40715.0
102781      1   0.0      61559.5      40715.0
102782      1   0.0      61559.5      40715.0
102783      1   0.0      61559.5      40715.0
102784      1   0.0      61559.5      40715.0
102785      1   0.0      61559.5      40715.0
102794      1   0.0      61559.5      40715.0
102795      1   0.0      61559.5      40715.0
102796      1   0.0      61559.5      40715.0
102797      1   0.0      61559.5      40715.0
102798      1   0.0      61559.5      40715.0
102801      1   0.0      61559.5      40715.0
102802      2   0.0      39021.5      40715.0
102803      1   0.0      61559.5      40715.0
102804      1   0.0      61559.5      40715.0
102805      1   0.0      61559.5      40715.0
102806      1   0.0      61559.5      40715.0

[77064 rows x 4 columns]

### 2. Работа с тестовой выборкой

In [6]:
ids_list = list()
for string in test_data.looked:
    id_list = string.strip().split(',')
    ids_list += id_list
ids_list = list(map(int, ids_list))

test_ids_set = set(ids_list)
dif = test_ids_set.difference(list(train_looks_buys_data.index))
dif_list = list(dif)

dif_data = pd.DataFrame(index = dif_list)
dif_data

train_looks_buys_data = train_looks_buys_data.append(dif_data)
train_looks_buys_data = train_looks_buys_data.fillna(0)
train_looks_buys_data

C:\Users\rusell\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\frame.py:6692: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)


bought_rank  buys  looked_rank  looks
0           40715.0   0.0      14211.5    6.0
1           40715.0   0.0      14211.5    6.0
2           40715.0   0.0       8828.0    9.0
3           40715.0   0.0      11933.5    7.0
4           40715.0   0.0       6734.0   11.0
5            2473.0   1.0      21598.5    4.0
6             367.0   2.0          9.0  283.0
7             367.0   2.0          6.0  312.0
8             110.0   3.0         13.0  225.0
9           40715.0   0.0      11933.5    7.0
10          40715.0   0.0      11933.5    7.0
11          40715.0   0.0      17263.5    5.0
12          40715.0   0.0       3508.0   17.0
13          40715.0   0.0       7697.5   10.0
14          40715.0   0.0      21598.5    4.0
16          40715.0   0.0        958.5   36.0
17            367.0   2.0        251.0   70.0
18          40715.0   0.0       6734.0   11.0
19          40715.0   0.0       1011.5   35.0
20          40715.0   0.0        555.5   48.0
21          40715.0   0.0       6734.0   11.0
22          40715.0   0.0        910.0   37.0
23          40715.0   0.0       2913.5   19.0
24          40715.0   0.0      11933.5    7.0
25          40715.0   0.0      14211.5    6.0
26          40715.0   0.0      11933.5    7.0
27          40715.0   0.0       4274.0   15.0
28            110.0   3.0         51.0  148.0
29           2473.0   1.0       3875.0   16.0
30           2473.0   1.0       1434.5   29.0
...             ...   ...          ...    ...
102739          0.0   0.0          0.0    0.0
102747          0.0   0.0          0.0    0.0
102754          0.0   0.0          0.0    0.0
102755          0.0   0.0          0.0    0.0
102756          0.0   0.0          0.0    0.0
102757          0.0   0.0          0.0    0.0
102758          0.0   0.0          0.0    0.0
102759          0.0   0.0          0.0    0.0
102760          0.0   0.0          0.0    0.0
102768          0.0   0.0          0.0    0.0
102769          0.0   0.0          0.0    0.0
102770          0.0   0.0          0.0    0.0
102771          0.0   0.0          0.0    0.0
102772          0.0   0.0          0.0    0.0
102773          0.0   0.0          0.0    0.0
102774          0.0   0.0          0.0    0.0
102775          0.0   0.0          0.0    0.0
102786          0.0   0.0          0.0    0.0
102787          0.0   0.0          0.0    0.0
102788          0.0   0.0          0.0    0.0
102789          0.0   0.0          0.0    0.0
102790          0.0   0.0          0.0    0.0
102791          0.0   0.0          0.0    0.0
102792          0.0   0.0          0.0    0.0
102793          0.0   0.0          0.0    0.0
102799          0.0   0.0          0.0    0.0
102800          0.0   0.0          0.0    0.0
102807          0.0   0.0          0.0    0.0
102808          0.0   0.0          0.0    0.0
102809          0.0   0.0          0.0    0.0

[102653 rows x 4 columns]

### 3. Задания

In [7]:
def get_metrics(looked, bought, data_type, k):
    bought_qty = 0
    
    looked_list = looked.strip().split(',')
    bought_list = bought.strip().split(',')
    
    looked_data = list(map(int, looked_list))
    bought_data = list(map(int, bought_list))

    l = len(looked_data)
    recom_numb = min(len(looked_data), int(k))
    looked_set = set(looked_data)
    result_list = train_looks_buys_data.loc[looked_set, data_type].sort_values(kind='mergesort')
    recommendations = list(result_list[0:recom_numb].index)
    
    for i in bought_data:
        if i in recommendations:
            bought_qty = bought_qty + 1
            
    precision = bought_qty / k
    recall = bought_qty / len(bought_data)
    return precision, recall

def get_metrics_for_k_array(data, k_array):
    data_rows = data.dropna()
    for row in data_rows.iterrows():
        row_id = row[0]
        row_looked = row[1]['looked']
        row_bougth = row[1]['bought']
        for k in k_array:
            for data_type in ['looked_rank','bought_rank']:
                precision, recall = get_metrics(row_looked, row_bougth, data_type, k)
                data.loc[row_id, 'precision k=' + str(k) + ' '+ data_type] = precision
                data.loc[row_id, 'recall k='+ str(k) + ' ' + data_type] = recall

In [8]:
k_array = [1,5]
get_metrics_for_k_array(train_data, k_array)
train_data

looked      bought  \
0                                            0,1,2,3,4,5         NaN   
1                                   9,10,11,9,11,12,9,11         NaN   
2                                      16,17,18,19,20,21         NaN   
3                                         24,25,26,27,24         NaN   
4                    34,35,36,34,37,35,36,37,38,39,38,39         NaN   
5                                                     42         NaN   
6                                               47,48,49         NaN   
7                 59,60,61,62,60,63,64,65,66,61,67,68,67    67,60,63   
8                                            71,72,73,74         NaN   
9                                               76,77,78         NaN   
10                   84,85,86,87,88,89,84,90,91,92,93,86          86   
11     114,77,115,116,117,118,119,120,121,120,122,123...         NaN   
12                               129,130,131,132,133,134         NaN   
13                93,137,138,139,140,141,142,141,143,144         NaN   
14                                 97,155,156,155,157,93         NaN   
15                        163,87,129,164,129,130,165,166         NaN   
16                                   173,174,175,174,176         NaN   
17                                               136,192         NaN   
18                                               195,196         NaN   
19                                       138,198,199,127         199   
20                                               206,207         NaN   
21                                               216,217         NaN   
22                                                   220         NaN   
23                                           223,224,225         NaN   
24               241,242,243,244,245,246,247,248,249,242         NaN   
25                                           253,254,169         NaN   
26                                       262,263,262,264         NaN   
27     265,266,267,268,269,270,269,268,271,272,273,27...         NaN   
28                                                   291         NaN   
29                                       296,297,298,299         NaN   
...                                                  ...         ...   
49970  102761,24754,48117,14732,162,46291,102762,1092...         NaN   
49971  9399,93922,23810,16769,10976,16580,102776,1027...         NaN   
49972  13344,13037,99575,22310,34469,16194,90788,2146...         NaN   
49973  10258,22738,982,17615,48769,102794,49168,1431,...         NaN   
49974    16024,8367,16024,17060,17061,75302,49246,102801         NaN   
49975                18211,40362,81465,86547,40362,81465         NaN   
49976                                1748,8509,8521,7594         NaN   
49977                                  56484,62543,57533         NaN   
49978                                   38846,16421,8321         NaN   
49979  20408,33706,41416,33706,41416,20408,41416,2040...         NaN   
49980                               390,4535,381,382,381         NaN   
49981                                   64552,25931,2807  25935,2807   
49982                             30508,2915,17064,38717         NaN   
49983                                          2582,3059         NaN   
49984                                              49195         NaN   
49985  35572,27139,42308,2503,49977,35569,17942,35569...         NaN   
49986                17711,21841,17711,21841,17711,21841         NaN   
49987  1480,2639,1480,1054,557,10991,1055,1054,10991,...         NaN   
49988                                  29504,14159,24162         NaN   
49989                                     9831,3059,2581         NaN   
49990                42379,64439,43687,47097,18694,32320         NaN   
49991            91921,20251,5063,21742,5063,20251,34927       91921   
49992                                102802,83951,102802         NaN   
49993                                  28165,24167,28165         NaN   
49994  99782,92081

### 4. Посчитаем средние значения

In [9]:
def get_avg_metrics(data, k_array):
    for k in k_array:
        for metric in ['recall', 'precision']:
            result_string = ''
            for data_type in ['looked_rank','bought_rank']:
                result_string += data_type + ' ' + metric + str(k) + '\t'
                result = data[metric + ' k=' + str(k) + ' ' + data_type].mean(skipna=True)
                rounded_result = round(result, 2)
                result_string += str(rounded_result) + '     '
            print(result_string)
    return

In [10]:
get_avg_metrics(train_data, k_array)

looked_rank recall1	0.44     bought_rank recall1	0.68     
looked_rank precision1	0.51     bought_rank precision1	0.79     
looked_rank recall5	0.82     bought_rank recall5	0.93     
looked_rank precision5	0.21     bought_rank precision5	0.25     


In [11]:
get_metrics_for_k_array(test_data, k_array)

In [12]:
test_data

looked   bought  \
0                                                  6,7,8      NaN   
1                                               13,14,15      NaN   
2                                                  22,23      NaN   
3                                      28,29,30,31,32,33      NaN   
4                                                  40,41      NaN   
5                                43,44,43,45,43,45,43,46      NaN   
6                       50,51,47,52,49,53,54,55,56,57,58      NaN   
7                          63,68,69,70,66,61,59,61,66,68    66,63   
8                                                     75      NaN   
9                                         79,80,81,82,83      NaN   
10     94,95,94,96,97,98,99,100,101,80,102,103,104,10...      NaN   
11                                       125,126,127,128      NaN   
12                                               135,136      NaN   
13               145,146,147,148,149,150,151,152,153,154      NaN   
14                               158,159,160,159,161,162      162   
15                     167,168,169,170,79,171,170,79,172      NaN   
16     177,178,179,180,181,178,182,183,184,185,186,90...      NaN   
17                                            93,193,194      NaN   
18                                           122,197,182      NaN   
19                                   200,201,202,203,204  201,205   
20                       208,209,210,211,212,213,214,215      NaN   
21                                               218,219      NaN   
22                                           221,222,221      NaN   
23     226,227,228,229,230,231,232,230,232,233,232,23...      NaN   
24                                           250,251,252      NaN   
25                       114,255,256,257,258,259,260,261      NaN   
26                                                   264      NaN   
27                           284,285,286,287,288,289,290      NaN   
28                                       292,293,294,295      NaN   
29                                       300,7,301,302,6      NaN   
...                                                  ...      ...   
49970  1869,36151,43923,3049,2845,56337,12802,49106,6...      NaN   
49971  42624,55383,8067,25513,31555,10361,93753,54591...      NaN   
49972  29965,18125,41086,11074,1262,58457,65283,43742...      NaN   
49973                    102799,102800,51579,64938,51579      NaN   
49974  16027,483,9989,22918,15922,26426,12842,26427,3...      NaN   
49975                      21150,26577,21150,26577,21150      NaN   
49976                                              59406      NaN   
49977  56484,20127,16894,30782,16899,30782,73872,1414...      NaN   
49978                                        38846,56484      NaN   
49979                 2539,11416,25567,11416,25567,11416      NaN   
49980                            25935,50601,84172,25935      NaN   
49981  127,138,804,5771,6688,62387,82091,8189,82091,2...      NaN   
49982                                    15237,8280,9470      NaN   
49983  72107,44288,89169,439,44288,28061,89169,28061,...      NaN   
49984  55813,2502,55813,17711,21841,22562,32506,2504,...      NaN   
49985  21841,17711,21841,17711,21841,17711,21841,1771...    21841   
49986                                     884,1867,17590      NaN   
49987  9911,14562,38351,408,1498,408,9726,70125,27239...      NaN   
49988                               2582,59783,2582,3059      NaN   
49989           6570,882,6570,6,882,6,2954,6570,882,9669      NaN   
49990                                   73,204,609,10765      NaN   
49991                  47538,1636,72785,33054,1636,13989      NaN   
49992                                        39006,63947      NaN   
49993                                          7537,1935      NaN   
49994        33049,9667,1858,13995,1857,14365,9111,34969      NaN   
49995                                  37637,18363,18131      NaN   
49996  35402,10150,35402,10150,35402,88962,49526